/* auto-generated by NAPI-RS */

/* eslint-disable */
export declare class AAM {
    constructor()

    merge(content: string): void

    mergeContent(content: string): void

    mergeFile(path: string): void

    findObj(key: string): string | null

    findKey(value: string): string | null

    findDeep(key: string): string | null

    findList(key: string): Array<string> | null

    findObject(key: string): Record<string, string> | null

    keys(): Array<string>

    toMap(): Record<string, string>

    validateValue(typeName: string, value: string): void

    close(): void

    isClosed(): boolean
}

export declare class AAMBuilder {
    constructor()

    addLine(key: string, value: string): void

    comment(text: string): void

    schema(name: string, fields: Array<string>): void

    schemaMultiline(name: string, fields: Array<string>): void

    derive(path: string, schemas: Array<string>): void

    import(path: string): void

    typeAlias(alias: string, typeName: string): void

    asString(): string
}

export type AAML = AAM

export type JsAam = AAM

export type JsAaml = AAML

export declare function load(path: string): AAM

export declare function parse(content: string): AAM

export declare function recoverSimple(content: string): AAM

export declare function version(): string
