/* auto-generated by NAPI-RS */

/* eslint-disable */
export declare class AAML {
    constructor()

    merge(content: string): void

    mergeContent(content: string): void

    mergeFile(path: string): void

    findObj(key: string): string | null

    findKey(value: string): string | null

    findDeep(key: string): string | null

    findList(key: string): Array<string> | null

    findObject(key: string): Record<string, string> | null

    keys(): Array<string>

    toMap(): Record<string, string>

    validateValue(typeName: string, value: string): void

    close(): void

    isClosed(): boolean
}

export type JsAaml = AAML

export declare function load(path: string): AAML

export declare function parse(content: string): AAML

export declare function version(): string
