[workspace]
members = ["aam-core", "aam-derive", "aam-rs"]
exclude = ["bindings"]
resolver = "2"

[workspace.package]
version = "2.7.1"
edition = "2024"
rust-version = "1.89.0"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/aam-rs/aam-rs"
authors = ["Nikita Goncharov <ininids@ininids.in.rs>"]

[workspace.dependencies]
aam-core = { path = "aam-core", version = "2.7.1" }
aam-derive = { path = "aam-derive", version = "2.7.1" }
