[package]
name = "aam_ruby"
version = "2.8.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aam-rs = { path = "../../../.." }
magnus = { git = "https://github.com/matsadler/magnus", features = ["embed"] }

[features]
reconstructer = ["aam-rs/reconstructer"]
