[package]
name = "aam-rs-node"
version = "2.3.0"
edition = "2024"
publish = false

[dependencies]
aam-rs = { path = "../..", features = ["translator"] }
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"

[lib]
name = "aam_rs_node"
crate-type = ["cdylib"]

