/* auto-generated by NAPI-RS */

/* eslint-disable */
export declare class AAM {
    constructor()

    format(content: string): string

    formatRange(content: string, startLine: number, endLine: number): string

    get(key: string): string | null

    keys(): Array<string>

    toMap(): Record<string, string>

    find(query: string): Record<string, string>

    deepSearch(pattern: string): Record<string, string>

    reverseSearch(targetValue: string): Array<string>

    schemaNames(): Array<string>

    typeNames(): Array<string>

    close(): void

    isClosed(): boolean

    update(): void

    updateFromText(content: string): void
}

export type JsAam = AAM

export declare class AAMBuilder {
    constructor()

    addLine(key: string, value: string): void

    comment(text: string): void

    schema(name: string, fields: Array<string>): void

    schemaMultiline(name: string, fields: Array<string>): void

    derive(path: string, schemas: Array<string>): void

    import(path: string): void

    typeAlias(alias: string, typeName: string): void

    asString(): string
}

export type JsAamBuilder = AAMBuilder

export declare class InlineObject {
    constructor()

    add(key: string, value: string): void

    toString(): string
}

export declare function format(content: string): string

export interface JsLspResult {
    diagnostics: Array<string>
    formatted?: string
}

export declare function load(path: string): AAM

export declare function lspAssist(content: string): JsLspResult

export declare function parse(content: string): AAM

export declare function reconstructSchema(name: string, contents: Array<string>): string

export declare function splitAam(content: string): Record<string, AAMBuilder>

export declare function version(): string

export declare function parseInlineToMap(content: string): Record<string, string>
