[package]
name = "aam-wasm"
description = "Wasm bindings for the AAM framework implemented in Rust."
repository = "https://github.com/ininids/aam-rs/tree/main/wasm"
version = "2.8.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aam-rs = { path = "../..", features = ["translator"] }
wasm-bindgen = "0.2.105"
js-sys = "0.3.82"

[features]
reconstructer = ["aam-rs/reconstructer"]

[dev-dependencies]
wasm-bindgen-test = "0.3.55"

